const skills = {
  kim: [
    {
      name: "Kim Cương Trảm",
      type: "normal",
      cost: { mana: 0, fury: 0 },
      multiplier: 1.0,
      furyGain: 30,
      description: "Một nhát chém cứng rắn như kim cương, sát thương cơ bản.",
    },
    {
      name: "Thiết Tỏa Liên",
      type: "mana",
      cost: { mana: 20, fury: 0 },
      multiplier: 1.5,
      furyGain: 10,
      description:
        "Xiềng xích bằng kim loại khóa chặt kẻ địch, gây sát thương lớn.",
    },
    {
      name: "Ngân Thạch Quyền",
      type: "mana",
      cost: { mana: 35, fury: 0 },
      multiplier: 2.0,
      furyGain: 15,
      description: "Cú đấm như sấm vang, xuyên thủng phòng ngự.",
    },
    {
      name: "Hoàng Kim Ấn",
      type: "mana",
      cost: { mana: 50, fury: 0 },
      multiplier: 2.5,
      furyGain: 20,
      description: "Ấn vàng giáng xuống, nghiền nát chiến trường.",
    },
    {
      name: "Thần Kim Giới",
      type: "fury",
      cost: { mana: 0, fury: 100 },
      multiplier: 4.0,
      furyGain: 0,
      description: "Kích hoạt toàn bộ sức mạnh của Kim, tấn công chí mạng.",
    },
  ],

  moc: [
    {
      name: "Thanh Mộc Kích",
      type: "normal",
      cost: { mana: 0, fury: 0 },
      multiplier: 1.0,
      furyGain: 30,
      description: "Thương gỗ xanh đâm tới, gây sát thương cơ bản.",
    },
    {
      name: "Sinh Cơ Vĩnh",
      type: "mana",
      cost: { mana: 20, fury: 0 },
      multiplier: 1.5,
      furyGain: 10,
      description:
        "Hấp thụ sinh khí thiên địa, hồi phục một phần máu đồng thời gây sát thương.",
    },
    {
      name: "Lục Diệp Trảm",
      type: "mana",
      cost: { mana: 35, fury: 0 },
      multiplier: 2.0,
      furyGain: 15,
      description: "Phiến lá hóa kiếm, sắc bén vô cùng.",
    },
    {
      name: "Mộc Giới Trận",
      type: "mana",
      cost: { mana: 50, fury: 0 },
      multiplier: 2.5,
      furyGain: 20,
      description: "Triệu hồi rừng cây vây hãm đối thủ, sát thương lớn.",
    },
    {
      name: "Thiên Mộc Diệt",
      type: "fury",
      cost: { mana: 0, fury: 100 },
      multiplier: 4.0,
      furyGain: 0,
      description: "Sức mạnh Mộc tộc bùng nổ, nghiền nát kẻ thù.",
    },
  ],

  thuy: [
    {
      name: "Lam Thủy Tiễn",
      type: "normal",
      cost: { mana: 0, fury: 0 },
      multiplier: 1.0,
      furyGain: 30,
      description: "Ngọn thủy tiễn bắn thẳng, sát thương cơ bản.",
    },
    {
      name: "Băng Tỏa Thuật",
      type: "mana",
      cost: { mana: 20, fury: 0 },
      multiplier: 1.5,
      furyGain: 10,
      description: "Đóng băng kẻ địch trong chốc lát, sát thương tăng.",
    },
    {
      name: "Hàn Băng Trảm",
      type: "mana",
      cost: { mana: 35, fury: 0 },
      multiplier: 2.0,
      furyGain: 15,
      description: "Kiếm băng lạnh buốt chém xuống, xuyên thủng máu thịt.",
    },
    {
      name: "Tuyết Lĩnh Hạ",
      type: "mana",
      cost: { mana: 50, fury: 0 },
      multiplier: 2.5,
      furyGain: 20,
      description: "Ngọn núi tuyết sụp đổ, cuốn trôi tất cả.",
    },
    {
      name: "Thủy Long Ấn",
      type: "fury",
      cost: { mana: 0, fury: 100 },
      multiplier: 4.0,
      furyGain: 0,
      description: "Triệu hồi Thủy Long đánh gục kẻ thù.",
    },
  ],

  hoa: [
    {
      name: "Xích Viêm Trảm",
      type: "normal",
      cost: { mana: 0, fury: 0 },
      multiplier: 1.0,
      furyGain: 30,
      description: "Một nhát chém rực lửa, sát thương cơ bản.",
    },
    {
      name: "Liệt Diễm Cầu",
      type: "mana",
      cost: { mana: 20, fury: 0 },
      multiplier: 1.5,
      furyGain: 10,
      description: "Cầu lửa bùng nổ, đốt cháy kẻ địch.",
    },
    {
      name: "Hỏa Phượng Minh",
      type: "mana",
      cost: { mana: 35, fury: 0 },
      multiplier: 2.0,
      furyGain: 15,
      description: "Phượng hoàng lửa lao xuống, thiêu đốt chiến trường.",
    },
    {
      name: "Thiên Viêm Trận",
      type: "mana",
      cost: { mana: 50, fury: 0 },
      multiplier: 2.5,
      furyGain: 20,
      description: "Trận pháp lửa trời bao phủ, kẻ thù không thể tránh.",
    },
    {
      name: "Vạn Hỏa Diệt",
      type: "fury",
      cost: { mana: 0, fury: 100 },
      multiplier: 4.0,
      furyGain: 0,
      description: "Hàng vạn ngọn lửa hội tụ, tiêu diệt tất cả.",
    },
  ],

  tho: [
    {
      name: "Thạch Phách Quyền",
      type: "normal",
      cost: { mana: 0, fury: 0 },
      multiplier: 1.0,
      furyGain: 30,
      description: "Cú đấm như đá tảng, sát thương cơ bản.",
    },
    {
      name: "Sơn Thể Thuật",
      type: "mana",
      cost: { mana: 20, fury: 0 },
      multiplier: 1.5,
      furyGain: 10,
      description: "Biến thân như núi, tăng thủ và giáp, gây sát thương.",
    },
    {
      name: "Hoàng Thổ Trảm",
      type: "mana",
      cost: { mana: 35, fury: 0 },
      multiplier: 2.0,
      furyGain: 15,
      description: "Kiếm đất bổ xuống, phá hủy phòng ngự.",
    },
    {
      name: "Thổ Long Kích",
      type: "mana",
      cost: { mana: 50, fury: 0 },
      multiplier: 2.5,
      furyGain: 20,
      description: "Triệu hồi Thổ Long, tạo động đất.",
    },
    {
      name: "Thiên Thạch Giới",
      type: "fury",
      cost: { mana: 0, fury: 100 },
      multiplier: 4.0,
      furyGain: 0,
      description: "Thiên thạch từ trời rơi xuống, sức hủy diệt kinh hoàng.",
    },
  ],
};

module.exports = skills;
